### ISSUE TITLE
feat: TensorRT-LLM Inflight batching 

### ISSUE THREAD

**Issue by tikikun** [janhq/cortex.tensorrt-llm#29]
Relevant docs can be found here.

https://nvidia.github.io/TensorRT-LLM/batch_manager.html#get-and-send-callbacks

Inflight batching is the most beneficial feature in CUDA system for LLM inferencing right now it can enable very high throughput.

**Comment by gabrielle-ong** [comment]
Deprecated due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
