### ISSUE TITLE
feat: TensorRT-LLM InferenceRequest and stop_words_list

### ISSUE THREAD

**Issue by tikikun** [janhq/cortex.tensorrt-llm#30]
<img width="1269" alt="image" src="https://github.com/janhq/nitro-tensorrt-llm/assets/22268502/b73f8589-01fc-4c48-93e3-192f8677683e">

**Comment by gabrielle-ong** [comment]
Deprecated due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
