### ISSUE TITLE
feat: TensorRT-LLM Request Interruption

### ISSUE THREAD

**Issue by tikikun** [janhq/cortex.tensorrt-llm#31]
Relevant docs can be found at

<img width="771" alt="image" src="https://github.com/janhq/nitro-tensorrt-llm/assets/22268502/20e601f6-2edd-4228-9e1e-5a2fe1cb7804">

**Comment by gabrielle-ong** [comment]
Deprecated due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
